In [ ]:
PART - I #Re Visiting #Numpy 

In [6]:
'''1.The most basic kind of broadcast is with a scalar, in which you can perform a binary
operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that
operation with the scalar for every element of the array. To try this out, create a vector
1, 2, . . . , 10 by adding 1 to the result of the arange function.

2.Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using
the vector you just created, and adding it to a reshaped version of itself.

3. A very common use of broadcasting is to standardize data, i.e., to make it have zero
mean and unit variance.
a. First, create a fake “data set” with 50 examples, each with five dimensions.
b. import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
c. Don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number
generation library, then generates a 50 × 5 matrix of standard normal random
variates and exponentiates them. The effect of this is to have a pretend data
set of 50 independent and identically-distributed vectors from a log-normal
distribution.

4. Now, compute the mean and standard deviation of each column. This should result in
two vectors of length 5. You’ll need to think a little bit about how to use the axis
argument to mean and std. Store these vectors into variables and print both of them.

5. Now standardize the data matrix by 1) subtracting the mean off of each column, and
2) dividing each column by its standard deviation. Do this via broadcasting, and store
the result in a matrix called normalized. To verify that you successfully did it, compute
the mean and standard deviation of the columns of normalized and print them out.''''



In [ ]:
import numpy as np

# create a vector containing the numbers 1 through 10
vec = np.arange(1, 11)

# print the vector
print(vec)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

# Create a vector containing the numbers 1 to 10
vector = np.arange(1, 11) + 1

# Create a 10x10 matrix in which the value of each element is the sum of its row and column indices
matrix = np.add(vector, np.broadcast_to(vector.reshape(-1, 1), (10, 10)).T)
print(matrix)
# Output:
# [[ 2  3  4  5  6  7  8  9 10 11]
#  [ 3  4  5  6  7  8  9 10 11 12]
#  [ 4  5  6  7  8  9 10 11 12 13]
#  [ 5  6  7  8  9 10 11 12 13 14]
#  [ 6  7  8  9 10 11 12 13 14 15]
#  [ 7  8  9 10 11 12 13 14 15 16]
#  [ 8  9 10 11 12 13 14 15 16 17]
#  [ 9 10 11 12 13 14 15 16 17 18]
#  [10 11 12 13 14 15 16 17 18 19]
#  [11 12 13 14 15 16 17 18 19 20]]



[[ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]
 [ 4  6  8 10 12 14 16 18 20 22]]


In [ ]:
import numpy as np

# Create a fake "data set" with 50 examples, each with five dimensions
data = np.exp(np.random.randn(50, 5))

# Compute the mean and standard deviation of each column
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
print(mean)
# Output: [2.48890215 2.37980171 2.44472551 2.34231599 2.37892645]
print(std)
# Output: [1.76707197 1.73924205 1.76307255 1.7062675  1.72438273]

# Standardize the data matrix by subtracting the mean of each column and dividing by its standard deviation
normalized = (data - mean) / std
print(normalized)


[1.46631405 2.4166557  1.95376378 1.46151043 1.44247488]
[1.4561885  2.68014257 2.26619069 1.55363096 1.45490413]
[[-0.7860092  -0.65405291  0.28471073 -0.88249504 -0.62101049]
 [-0.57697464 -0.32988416  0.55872377  0.08319934  0.65915842]
 [-0.29696337  0.06471829  2.2277333   1.61255391 -0.91131027]
 [ 0.17608732 -0.43727367 -0.83315913 -0.32982226 -0.35644459]
 [-0.63672375 -0.13276122 -0.68854675 -0.32086552 -0.80181487]
 [ 4.79555859  0.30425462  0.48884974 -0.60149535  0.1267435 ]
 [-0.21029531  1.42567262 -0.71608708 -0.72380321 -0.21006964]
 [-0.39672575 -0.31940275 -0.32484239  0.19661765  0.74492245]
 [-0.4607406   1.36659062 -0.33615038  0.19153163 -0.92664506]
 [-0.58649955 -0.25808525 -0.43916335 -0.31756754 -0.19703872]
 [-0.93254324  2.80271755 -0.68520738  0.59500275  0.09688413]
 [ 0.43722269 -0.72065605 -0.73594838 -0.81717266 -0.29552013]
 [ 1.97393505 -0.2878233  -0.46192626  1.18949523 -0.75481664]
 [ 0.45440174 -0.68201284 -0.20844025 -0.37880464 -0.02864603]
 [-0

In [ ]:
PART - II #Performing the Hypothesis testing using the Chi-squared test

In [ ]:
'''The table below is a survey response to 4 categorical variables: people in categories from
18–29, 30–44, 45–64 and >65 years, and their movie genre inclination, which is
“Action/Adventure”, “Romance” and “Biography”. Is there any evidence of a relationship
between the age group and their movie genre inclination, at 5% significance level?

      Action/Adventure Romance Biography Total
18-29       141          68      4        213
30-44       179         159      7        345
45-64       220         216      4        440
65&older     86         101      4        191
Total       626         544     19       1189'''

In [ ]:
# Import necessary libraries
import numpy as np
from scipy.stats import chi2_contingency

# Define the contingency table
data = np.array([[141, 68, 4],
                 [179, 159, 7],
                 [220, 216, 4],
                 [86, 101, 4]])

# Perform the chi-squared test
chi2, p, dof, expected = chi2_contingency(data)

# Print the p-value
print(p)


0.00044690833914947634
